version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfiles/app/Dockerfile
    image: yii2-demo-php:latest
    environment:
      - 'COMPOSER_AUTH={"github.com": "dbd6c5966b80f1379ad6c341fef220b8206ae985"}'
      - 'POD_NAME=phpfpm'
    volumes:
      - ./Dockerfiles/app/php/php-dev.ini:/usr/local/etc/php/php.ini
      - ./:/app
    depends_on:
      - postgresql
  nginx:
    build:
      context: Dockerfiles/nginx
    image: yii2-demo-nginx:latest
    ports:
      - '8888:80'
    volumes:
      - ./:/app
    links:
      - app
  postgresql:
    build:
      context: Dockerfiles/postgresql
    image: yii2-demo-postgresql:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
    volumes:
      - ./.pg_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
  python:
    build:
      context: Dockerfiles/python
    image: python-demo:latest
    ports:
      - '5555:5000'
    volumes:
      - ./:/app
    depends_on:
      - app
